### PR TITLE
Additional minor improvements

### PR DESCRIPTION
**Pull request by adams85**
### Describe the purpose of your pull request

* Improves error reporting when setting type and default value type mismatch. Firstly, makes `GetValue<T>`, `GetValueDetails<T>`, etc. methods fail early if the specified CLR type is not supported. Secondly, provides a meaningful error message when the specified CLR type and the setting type mismatch.
* Improves ConfigDeserializer performance by using HTTP ETag for change detection instead of calculating a hash.
* Improves SHA1 hashing implementation by changing the logic so it doesn't new up an SHA1 instance on each hash calculation (as this could be [fairly expensive](https://stackoverflow.com/a/74211393/8656352)).
* Eliminates ModuleInitalizer trick used in tests as I've learned it's unnecessary because MSTest provides that feature out of the box.

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

### CODE REVIEW

**Comment by adams85** [comment]
Looks like Sonar doesn't like SHA1 :( How to make it understand that it's safe in this case?

**Comment by z4kn4fein** [comment]
> Looks like Sonar doesn't like SHA1 :( How to make it understand that it's safe in this case?

Did it for ya!

**Comment by adams85** [comment]
You're the man! Thanks 👍

**Review by endret — CHANGES_REQUESTED** [review]

**Comment by sigewuzhere** [comment]
Please point me to the right direction. Where did the UX change? Which files should I focus on?

**Comment by adams85** [comment]
Only the first commit is relevant from the UX standpoint. First of all, there's a Trello ticket about improving the error message when the type of the default value and the type of the actual value mismatch. This is done [here](https://github.com/configcat/.net-sdk/pull/51/commits/6d62a8c65f5bf1d2464bdd3c063e0f3ab8d0537b#diff-e53563e3fe29251a2c13adec55b8021190b6355694e18fc29d3c9164301ed85cR24). On top of that, I also improved [the logic of the `GetValueXXX` methods](https://github.com/configcat/.net-sdk/pull/51/commits/6d62a8c65f5bf1d2464bdd3c063e0f3ab8d0537b#diff-df6f61895a221fbd41863c9b221af7275a6e9947248c57bf6dde7fe33549e26eR260) to fail early if the default value type is not supported. This also aligns the behavior with other SDKs like the Swift one.

**Review by sigewuzhere — APPROVED** [review]

**Review by endret — APPROVED** [review]

**Pull request merged**
